name: Terraform Validation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Validate Terraform Configurations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Check Day 1 - Terraform Format
        working-directory: ./day1
        run: terraform fmt -check -recursive

      - name: Check Day 1 - Terraform Init
        working-directory: ./day1
        run: terraform init -backend=false

      - name: Check Day 1 - Terraform Validate
        working-directory: ./day1
        run: terraform validate

      - name: Check Day 2 - Terraform Format
        working-directory: ./day2
        run: terraform fmt -check -recursive

      - name: Check Day 2 - Terraform Init
        working-directory: ./day2
        run: terraform init -backend=false

      - name: Check Day 2 - Terraform Validate
        working-directory: ./day2
        run: terraform validate

      - name: Check Day 3 - Terraform Format
        working-directory: ./day3
        run: terraform fmt -check -recursive

      - name: Check Day 4 - Terraform Format
        working-directory: ./day4
        run: terraform fmt -check -recursive
